spring:
  profiles:
    active:
      -dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.1.27:3306/cloudDB01
    username: root
    password: yubing1126
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

    mybatis:
      type-aliases-package: tk.yubing.springcloud.entities
      mapper-locations: -classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
  instance-id: dept-8001.com
  prefer-ip-address: true
info:
  app.name: yubing-microservicecloud-config01
  company.name: www.yubing.tk
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8002
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.1.27:3306/cloudDB02
    username: root
    password: yubing1126
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  mybatis:
    type-aliases-package: tk.yubing.springcloud.entities
    mapper-locations: -classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7002.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: yubing-microservicecloud-config02
  company.name: www.yubiong.tk
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
